# Source language and JDK version to use.
language: java
jdk: oraclejdk7

# Compile and package JAR.
install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}

# Disable email notification for now
notifications:
  email: false